/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServerSideRenderedRouteImport } from './routes/server-side-rendered'
import { Route as ClientSideRenderedRouteImport } from './routes/client-side-rendered'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerSideRenderedIdRouteImport } from './routes/server-side-rendered_.$id'
import { Route as ClientSideRenderedIdRouteImport } from './routes/client-side-rendered_.$id'

const ServerSideRenderedRoute = ServerSideRenderedRouteImport.update({
  id: '/server-side-rendered',
  path: '/server-side-rendered',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSideRenderedRoute = ClientSideRenderedRouteImport.update({
  id: '/client-side-rendered',
  path: '/client-side-rendered',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerSideRenderedIdRoute = ServerSideRenderedIdRouteImport.update({
  id: '/server-side-rendered_/$id',
  path: '/server-side-rendered/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSideRenderedIdRoute = ClientSideRenderedIdRouteImport.update({
  id: '/client-side-rendered_/$id',
  path: '/client-side-rendered/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client-side-rendered': typeof ClientSideRenderedRoute
  '/server-side-rendered': typeof ServerSideRenderedRoute
  '/client-side-rendered/$id': typeof ClientSideRenderedIdRoute
  '/server-side-rendered/$id': typeof ServerSideRenderedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client-side-rendered': typeof ClientSideRenderedRoute
  '/server-side-rendered': typeof ServerSideRenderedRoute
  '/client-side-rendered/$id': typeof ClientSideRenderedIdRoute
  '/server-side-rendered/$id': typeof ServerSideRenderedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client-side-rendered': typeof ClientSideRenderedRoute
  '/server-side-rendered': typeof ServerSideRenderedRoute
  '/client-side-rendered_/$id': typeof ClientSideRenderedIdRoute
  '/server-side-rendered_/$id': typeof ServerSideRenderedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client-side-rendered'
    | '/server-side-rendered'
    | '/client-side-rendered/$id'
    | '/server-side-rendered/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client-side-rendered'
    | '/server-side-rendered'
    | '/client-side-rendered/$id'
    | '/server-side-rendered/$id'
  id:
    | '__root__'
    | '/'
    | '/client-side-rendered'
    | '/server-side-rendered'
    | '/client-side-rendered_/$id'
    | '/server-side-rendered_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientSideRenderedRoute: typeof ClientSideRenderedRoute
  ServerSideRenderedRoute: typeof ServerSideRenderedRoute
  ClientSideRenderedIdRoute: typeof ClientSideRenderedIdRoute
  ServerSideRenderedIdRoute: typeof ServerSideRenderedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/server-side-rendered': {
      id: '/server-side-rendered'
      path: '/server-side-rendered'
      fullPath: '/server-side-rendered'
      preLoaderRoute: typeof ServerSideRenderedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-side-rendered': {
      id: '/client-side-rendered'
      path: '/client-side-rendered'
      fullPath: '/client-side-rendered'
      preLoaderRoute: typeof ClientSideRenderedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-side-rendered_/$id': {
      id: '/server-side-rendered_/$id'
      path: '/server-side-rendered/$id'
      fullPath: '/server-side-rendered/$id'
      preLoaderRoute: typeof ServerSideRenderedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-side-rendered_/$id': {
      id: '/client-side-rendered_/$id'
      path: '/client-side-rendered/$id'
      fullPath: '/client-side-rendered/$id'
      preLoaderRoute: typeof ClientSideRenderedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientSideRenderedRoute: ClientSideRenderedRoute,
  ServerSideRenderedRoute: ServerSideRenderedRoute,
  ClientSideRenderedIdRoute: ClientSideRenderedIdRoute,
  ServerSideRenderedIdRoute: ServerSideRenderedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
