/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaRouteImport } from './routes/spa'
import { Route as MpaRouteImport } from './routes/mpa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpaIdRouteImport } from './routes/spa_.$id'
import { Route as MpaIdRouteImport } from './routes/mpa_.$id'

const SpaRoute = SpaRouteImport.update({
  id: '/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const MpaRoute = MpaRouteImport.update({
  id: '/mpa',
  path: '/mpa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaIdRoute = SpaIdRouteImport.update({
  id: '/spa_/$id',
  path: '/spa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MpaIdRoute = MpaIdRouteImport.update({
  id: '/mpa_/$id',
  path: '/mpa/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mpa': typeof MpaRoute
  '/spa': typeof SpaRoute
  '/mpa/$id': typeof MpaIdRoute
  '/spa/$id': typeof SpaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mpa': typeof MpaRoute
  '/spa': typeof SpaRoute
  '/mpa/$id': typeof MpaIdRoute
  '/spa/$id': typeof SpaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mpa': typeof MpaRoute
  '/spa': typeof SpaRoute
  '/mpa_/$id': typeof MpaIdRoute
  '/spa_/$id': typeof SpaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mpa' | '/spa' | '/mpa/$id' | '/spa/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mpa' | '/spa' | '/mpa/$id' | '/spa/$id'
  id: '__root__' | '/' | '/mpa' | '/spa' | '/mpa_/$id' | '/spa_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MpaRoute: typeof MpaRoute
  SpaRoute: typeof SpaRoute
  MpaIdRoute: typeof MpaIdRoute
  SpaIdRoute: typeof SpaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spa': {
      id: '/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof SpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mpa': {
      id: '/mpa'
      path: '/mpa'
      fullPath: '/mpa'
      preLoaderRoute: typeof MpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spa_/$id': {
      id: '/spa_/$id'
      path: '/spa/$id'
      fullPath: '/spa/$id'
      preLoaderRoute: typeof SpaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mpa_/$id': {
      id: '/mpa_/$id'
      path: '/mpa/$id'
      fullPath: '/mpa/$id'
      preLoaderRoute: typeof MpaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MpaRoute: MpaRoute,
  SpaRoute: SpaRoute,
  MpaIdRoute: MpaIdRoute,
  SpaIdRoute: SpaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
