/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaRouteImport } from './routes/spa'
import { Route as MpaRouteImport } from './routes/mpa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpaDetailRouteImport } from './routes/spa_.detail'
import { Route as MpaDetailRouteImport } from './routes/mpa_.detail'

const SpaRoute = SpaRouteImport.update({
  id: '/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const MpaRoute = MpaRouteImport.update({
  id: '/mpa',
  path: '/mpa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaDetailRoute = SpaDetailRouteImport.update({
  id: '/spa_/detail',
  path: '/spa/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const MpaDetailRoute = MpaDetailRouteImport.update({
  id: '/mpa_/detail',
  path: '/mpa/detail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mpa': typeof MpaRoute
  '/spa': typeof SpaRoute
  '/mpa/detail': typeof MpaDetailRoute
  '/spa/detail': typeof SpaDetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mpa': typeof MpaRoute
  '/spa': typeof SpaRoute
  '/mpa/detail': typeof MpaDetailRoute
  '/spa/detail': typeof SpaDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mpa': typeof MpaRoute
  '/spa': typeof SpaRoute
  '/mpa_/detail': typeof MpaDetailRoute
  '/spa_/detail': typeof SpaDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mpa' | '/spa' | '/mpa/detail' | '/spa/detail'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mpa' | '/spa' | '/mpa/detail' | '/spa/detail'
  id: '__root__' | '/' | '/mpa' | '/spa' | '/mpa_/detail' | '/spa_/detail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MpaRoute: typeof MpaRoute
  SpaRoute: typeof SpaRoute
  MpaDetailRoute: typeof MpaDetailRoute
  SpaDetailRoute: typeof SpaDetailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spa': {
      id: '/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof SpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mpa': {
      id: '/mpa'
      path: '/mpa'
      fullPath: '/mpa'
      preLoaderRoute: typeof MpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spa_/detail': {
      id: '/spa_/detail'
      path: '/spa/detail'
      fullPath: '/spa/detail'
      preLoaderRoute: typeof SpaDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mpa_/detail': {
      id: '/mpa_/detail'
      path: '/mpa/detail'
      fullPath: '/mpa/detail'
      preLoaderRoute: typeof MpaDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MpaRoute: MpaRoute,
  SpaRoute: SpaRoute,
  MpaDetailRoute: MpaDetailRoute,
  SpaDetailRoute: SpaDetailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
